version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789

  #Backend
  django_1:
    build: backend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  vue:
    container_name: "VueJS"
    build: ./frontend/vue-vuex/.
    working_dir: /app
    command: bash -c "npm install && npm run serve"
    ports:
      - "4000:8080"
    volumes:
      - ./frontend/vue-vuex:/app
    depends_on:
      - django_1
      - db
